### ISSUE TITLE
Idle downstream actors until confirmation is send

### ISSUE THREAD

**Issue by gabrielgiussi** [cakesolutions/scala-kafka-client#32] opened 2016-05-30 01:39 UTC
Watching the KafkaConsumerActor API I understand that the only way of process N messages batches from the same topic concurrently is creating N KafkaConsumerActor with the **same groupId** and each one with his own corresponding downstream actor.
From [KafkaConsumerActor](https://github.com/cakesolutions/scala-kafka-client/blob/605e391d6b88cb505dc465d46ea9264b4d0d5275/akka/src/main/scala/cakesolutions/kafka/akka/KafkaConsumerActor.scala).
> Before the actor continues pulling more data from Kafka, the receiver of the data must confirm the batches by sending back a [[KafkaConsumerActor.Confirm]] message that contains the offsets from the received batch.

If we want to achieve **at-least-once** semantics we must wait until each batch processing succeeds in order to send the Confirm message with the offsets.
So, although the downstream actor is not blocked (assuming we've done things right processing the batch async, e.g in a Future) it won't receive more batches until the Confirmation(offsets) is send and I see this being equal to blocking the actor.
Suppose the first batch contains messages 
`first message`
`second message`
`third message`
I writes this messages to a Mongo DB in a Future and send a confirmation message to the KafkaConsumerActor when this Futures succeeds.
If new messages comes
`fourth message`
`fifth message`
I would like to be able to process this new messages even if the first write to Mongo hasn't finished.
Until Mongo confirm the writes the downstream actor will be in a idle state, so why KafkaConsumerActor couldn't keep sending new batches?
I understand that this works as a mechanism to avoid overwhelming the downstream actor

> This mechanism allows the receiver to control the maximum rate of messages it will receive.

But we couldn't configure a threshold of batches that can be sent without confirmation? Something like split the unconfirmed state in unconfirmedThresholdUnreached and unconfirmedThresholdReached.
![states](https://cloud.githubusercontent.com/assets/7468185/15637420/45baba68-25ed-11e6-9e91-5d3c95bfe71a.png)

If creating N KafkaConsumerActor + downstream actor (with same groupid) is the way to go, I must choose a fixed number of actors?

I hope I've made myself clear.
Thanks!

**Comment by jkpl** [comment] 2016-05-30 20:24
Hi, thanks for the questions.

> Watching the KafkaConsumerActor API I understand that the only way of process N messages batches from the same topic concurrently is creating N KafkaConsumerActor with the same groupId and each one with his own corresponding downstream actor.

You can certainly parallelize message consumption by creating multiple consumer actors with the same group ID. The downstream actors must either be separate or be able to distinguish between the consumer actors (e.g. by sender reference). This pattern is really useful in multi-node systems, i.e. in separate JVMs hosted on separate machines. I'm not sure how much use you would get from using multiple consumers inside one node. You will also want to adjust the amount of the partitions in the topic according to how many consumers you want. The [Kafka documentation](https://kafka.apache.org/documentation.html) is pretty good at getting started with these kinds of questions.

> If we want to achieve at-least-once semantics we must wait until each batch processing succeeds in order to send the Confirm message with the offsets.

Correct.

> So, although the downstream actor is not blocked (assuming we've done things right processing the batch async, e.g in a Future) it won't receive more batches until the Confirmation(offsets) is send and I see this being equal to blocking the actor.

If you mean that blocking is the same as actor not getting new messages, then yes. However, it is most likely not blocking the underlying thread that the actor uses. While the actor is not processing anything, it's not using any thread resources either. I believe this is the default behaviour in Akka.

> I would like to be able to process this new messages even if the first write to Mongo hasn't finished.
Until Mongo confirm the writes the downstream actor will be in a idle state, so why KafkaConsumerActor couldn't keep sending new batches?
I understand that this works as a mechanism to avoid overwhelming the downstream actor

You answered your own question. :-) We use the confirm pattern to allow users to control when they are ready to receive more records. If the driver sends more than what is requested, it's violating this contract. Therefore, the maximum rate of messages consumed from Kafka depends on how fast your downstream actors are at processing messages.

If you want your downstream actor to receive more records, you could confirm the earlier batch before it has finished processing it. We haven't tried this (because we have no need for it so far), so be careful with this approach. Note that if your Mongo driver is slow at doing it's job, the work can easily pile up on the Mongo driver if you don't limit the rate at which you consume messages from Kafka.

There is a mechanism in the consumer actor that helps getting batches rapidly between confirmations. The consumer actor tries to buffer exactly one batch of messages while it's waiting for a confirmation from the downstream actor. This means that the consumer actor can immediately serve the next batch from memory after the downstream actor has confirmed the previous batch.

You can also tune the size of the batches that you receive from the consumer. For example, the consumer will pull a batch that is at maximum the size of [max.partition.fetch.bytes](https://kafka.apache.org/090/documentation.html#newconsumerconfigs), if it can. If your Kafka topic is filled with messages, the batch sizes should be fairly large by default. You can try tuning the consumer configuration to find the best fit for your use-case.

> But we couldn't configure a threshold of batches that can be sent without confirmation? Something like split the unconfirmed state in unconfirmedThresholdUnreached and unconfirmedThresholdReached.

It is true that some of the actors in the downstream chain might not have work to do while a batch is being processed in different parts of the chain. However, it might not be an actual problem in terms of performance. If the work in your actor system is more dependent on IO than CPU, then you probably wont get that much use from having multiple batches on the fly. In any case, I'll have a think about this more. Meanwhile, I recommend profiling your application's performance, if you're concerned about it. 

> If creating N KafkaConsumerActor + downstream actor (with same groupid) is the way to go, I must choose a fixed number of actors?

I'm not sure what you mean with this. Can you clarify?

**Comment by gabrielgiussi** [comment] 2016-06-01 02:33
First of all let me say great answer, very detailed.

> I'm not sure how much use you would get from using multiple consumers inside one node.

As far as I see, with a single downstream actor the processing of the batches is serialized, in contrast, if I were using N downstream actors, **even in a single node**, I could process batches concurrently.

> If you mean that blocking is the same as actor not getting new messages, then yes.

Indeed I wrote "blocking" in that sense, but I agree that the underlying thread is not blocked so this is a benefit but the actor being idle makes me some noise.

> If you want your downstream actor to receive more records, you could confirm the earlier batch before it has finished processing it

I really want at-least-once message delivery semantics, so this is not an option IMHO.

> Note that if your Mongo driver is slow at doing it's job, the work can easily pile up on the Mongo driver if you don't limit the rate at which you consume messages from Kafka.

Yes, I totally agree and I think this is an important point, especially if the Mongo driver or any API that I could be consuming doesn't have mechanisms for back-pressure.

> This means that the consumer actor can immediately serve the next batch from memory after the downstream actor has confirmed the previous batch.

This is a nice feature but it still doesn't save the downstream actor of consuming batches in a serialized manner (e.g. "after the downstream actor has confirmed the previous batch").

> You can also tune the size of the batches that you receive from the consumer.

Previous answer applies here too. For this being a solution it wil need be accompanied with a "tuned" Conf.scheduleInterval (aka Poll latency) that would give time to producers to "accummulate" a batch with the full size in the broker. This has the cost of a greater gap between the time a producer send a message and the time the consumer see it.
I mean, if a producer sends a message right after the consumer fetches the broker, it doesn't matter how big may be the batch, it won't be sended until the Mongo writes completes.
Suppose a batch size of 10 messages.
 1. Producer A sends message "Message A" to the broker
 2. Producer B sends message "Message B" to the broker
 3. KafkaConsumerActor fetches a batch with Messages (Message A, Message B) and sends it to ReceiverActor
 4. ReceiverActor receives the batch and sends a request to a third party API (i.e. MongoDB)
 5. Producer A sends a message "New Message from A" to the broker   // ReceiverActor idle
 6. Producer X sends a message Y to the broker                                  // ReceiverActor idle
 7. KafkaConsumerActor fetches a batch an buffer it (because has unconfirmed messages) //  ReceiverActor idle
 8. Third Party API sends response
 9. ReceiverActor send Confirm(offsets) to KafkaConsumerActor
 10. KafkaConsumerActor sends a buffered batch immediately

> If the work in your actor system is more dependent on IO than CPU, then you probably wont get that much use from having multiple batches on the fly.

Here I get a little confused. If my ReceiverActor is IO-bounded then the latency of the request to the third party API is a main issue.
In the current situation where the KafkaConsumerActor waits until confirmation for sending new batches to his downstream actor, the latency of the processing of each batch (e.g. writing it to Mongo) affects the others.

Current situation:
```
+-------+---------------------------+---------------------------+
| order |          batch 1          |          batch 2          |
+-------+---------------------------+---------------------------+
|     1 | KafkaConsumerActor fetch  |                           |
|     2 | ReceiverActor receive     | KafkaConsumerActor fetch  |
|     3 | Mongo write begins        |                           |
|     4 | Mongo write ends          |                           |
|     5 |                           | ReceiverActor receive     |
|     6 |                           | Mongo write begins        |
|     7 |                           | Mongo write ends          |
+-------+---------------------------+---------------------------+
```

Without waiting offsets confirmation: 
```
+-------+---------------------------+---------------------------+
| order |          batch 1          |          batch 2          |
+-------+---------------------------+---------------------------+
|     1 | KafkaConsumerActor fetch  |                           |
|     2 | ReceiverActor receive     | KafkaConsumerActor fetch  |
|     3 | Mongo write begins        | ReceiverActor receive     |
|     4 | Mongo write ends          | Mongo write begins        |
|     5 |                           | Mongo write ends          |
+-------+---------------------------+---------------------------+
```



> If creating N KafkaConsumerActor + downstream actor (with same groupid) is the way to go, I must choose a fixed number of actors?
**I'm not sure what you mean with this. Can you clarify?**

The number of ReceiverActor for processing batches concurrently must be fixed at startup or could I create new instances of ReceiverActor at runtime if they are needed (e.g. the KafkaConsumerActor is always buffering batches)?

Thanks for your time and patience.

**Comment by jkpl** [comment] 2016-06-05 21:26
> Here I get a little confused. If my ReceiverActor is IO-bounded then the latency of the request to the third party API is a main issue.

What I mean is that if you don't do much CPU heavy processing, but instead have one IO bound component in the middle of the actor chain, the amount of time spent in the those actors is very small compared to the time spent in IO. Therefore, you might not get much performance boost by having those actors do work simultaneously to the component doing the IO.

However, if you do have multiple components in the chain doing IO on batches, I can see the reason for wanting to have multiple batches "on the fly". For now, we don't provide a solution for that situation, but we may tackle it soon, if we find a satisfactory solution. I'll have to look into more on what are the potential caveats of having multiple batches on the fly, and how we handle those internally in the KafkaConsumerActor.

For now, you can restructure your code in a way that it splits one batch into multiple concurrent jobs consisting of multiple IO actions, which are then joined back into one result. I believe this will give you pretty good resource usage as well.

Regarding the whole issue, I'll have to do some more research. I will take your proposed solution in consideration when I discuss the problem more with my colleagues. Meanwhile, I'll keep this issue open.

**Comment by simonsouter** [comment] 2016-06-11 17:13
Great discussion.  I think the multiple batch idea proposed by @gabrielgiussi would certainly improve the performance of a single stream in the scenario as described.  There is a clear latency introduced in awaiting the downstream system's (mongo) confirmation of the batch before getting the next one.

Providing a capability to process multiple batches concurrently does introduce some complexity however, which is described here: (https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html) in section "Decouple Consumption and Processing".  Specifically it becomes tricky to keep the commit position consistent and ordering  guarantees are lost.

It would seem more reasonable to me to go with the original suggestion of using multiple KafkaConsumerActors with the same "groupId" to achieve the performance optimisation (downstream batch parallelism), rather than add the additional configuration and implementation complexity to the KafkaConsumerActor.  Since the ordering of the stream could not easily be guaranteed using the multiple batch technique, it makes sense to break up the stream into multiple ones and lean on the group capabilities already provided by the underlying driver.

**Comment by gabrielgiussi** [comment] 2016-06-13 16:20
Good point @simonsouter. 

> Decouple Consumption and Processing
> - CON: Guaranteeing order across the processors requires particular care as the threads will execute independently an earlier chunk of data may actually be processed after a later chunk of data just due to the luck of thread execution timing. For processing that has no ordering requirements this is not a problem.
> - CON: Manually committing the position becomes harder as it requires that all threads co-ordinate to ensure that processing is complete for that partition. 

So, the next thing I've got to do is choose between use a fixed number of KafkaConsumerActor created at application startup or create KafkaConsumerActors as needed, this requires some mechanism that let me know when my ReceiverActors are overwhelmed (could KafkaConsumerActors constantly entering in bufferFull state act as a signal of that?)
I'm thinking in elasticity here, e.g be capable of processing a peak load of Kafka messages buy maybe I'm going to far.

**Closed** 2016-07-01 19:12 UTC
